# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: debug-statements
      - id: check-added-large-files
        args: ['--maxkb=800']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.20
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v2.1.0'
    hooks:
      - id: mypy
  - repo: https://github.com/seddonym/import-linter
    rev: v2.11
    hooks:
      - id: import-linter
        name: '[Imports] Lint'
        stages:
          - pre-commit
        files: '^jiratui*'
        exclude: ^.*\/docs\/.*$
