# This workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "Run Tests"

permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - MacOs-latest
        py:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install libmagic on macOS
      if: runner.os == 'macOS'
      run: brew install libmagic
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.6.3"
        enable-cache: true
    - run: uv python install
    - name: Install Dependencies
      run: uv sync --all-extras --group test
    - name: Run Tests
      run: |
          uv run make test
    - name: Store snapshot report on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Snapshot Report ${{ matrix.os }} ${{ matrix.py }}
        path: ./snapshot_report.html
